### Categorias
GET http://localhost:3000/api/categorias
Accept: application/json

### Categoria
GET http://localhost:3000/api/categorias/9
Accept: application/json

### Nueva categoria
POST http://localhost:3000/api/categorias
Content-Type: application/json

{
    "nombre": "prueba"
}

### Articulos
GET http://localhost:3000/api/articulos
Accept: application/json

### Aires
GET http://localhost:3000/api/articulos?nombre=aire
Accept: application/json

### Aires en la pagina 2
GET http://localhost:3000/api/articulos?nombre=aire&pagina=2
Accept: application/json

### Nuevo articulo
POST http://localhost:3000/api/articulos
Content-Type: application/json

{
    "nombre": "PC GAMER",
    "precio": 1000000,
    "codigoDeBarra": "6969696969696",
    "idCategoria": 9,
    "stock": 10,
    "fechaAlta": "2025-05-23",
    "activo": true
}

### Modificar articulo
PUT http://localhost:3000/api/articulos/202
Content-Type: application/json

{
    "nombre": "PC GAMER",
    "precio": 2000000,
    "codigoDeBarra": "6969696969696",
    "idCategoria": 9,
    "stock": 1,
    "fechaAlta": "2025-05-23",
    "activo": true
}

### Borrar articulo
DELETE http://localhost:3000/api/articulos/1
Accept: application/json

### Borrar fisicamente articulo
DELETE http://localhost:3000/api/articulos/206?fisica=true
Accept: application/json

### Iniciar sesion jefe
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "usuario": "admin",
    "clave": "123"
}

### Iniciar sesion usuario
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "usuario": "juan",
    "clave": "123"
}

### Cerrar sesion
POST http://localhost:3000/api/logout
Content-Type: application/json
Authorization: Bearer <copiar refresh token>

### Renovar token acceso
POST http://localhost:3000/api/refreshtoken
Content-Type: application/json

{
    "refreshToken": "<copiar token>"
}

### Usuarios
GET http://localhost:3000/api/usuarios
Accept: application/json
Authorization: Bearer <copiar access token>
