### Mostrar todas
GET http://localhost:3000/api/temporadas
Content-Type: application/json

### Mostrar Stranger Things
GET http://localhost:3000/api/temporadas?titulo=Stranger%20Things
Content-Type: application/json

### Mostrar las de Netflix
GET http://localhost:3000/api/temporadas?plataforma=Netflix
Content-Type: application/json

### Mostrar las comedias
GET http://localhost:3000/api/temporadas?genero=comedia
Content-Type: application/json

### Mostrar las ultimas agregadas
GET http://localhost:3000/api/temporadas/ultimas
Content-Type: application/json

### Crear una temporada de Stranger Things
POST http://localhost:3000/api/temporadas
Content-Type: application/json

{
    "idSerie": 1,
    "numero": 3,
    "episodios": 5,
    "estreno": 2025,
    "genero": "Ciencia ficción",
    "creador": "yo"
}

### Crear fail
POST http://localhost:3000/api/temporadas
Content-Type: application/json

{
    "idSerie": 1,
    "numero": 4,
    "estreno": 2025,
    "episodios": 1,
    "genero": "hola",
    "creador": "yo"
}

### Actualizar
PUT http://localhost:3000/api/temporadas/11
Content-Type: application/json

{
    "idSerie": 1,
    "numero": 3,
    "episodios": 4,
    "estreno": 2025,
    "genero": "Ciencia ficción",
    "creador": "yo"
}

### Borrar
DELETE http://localhost:3000/api/temporadas/12
Content-Type: application/json