### Obtener la respuesta de la API en la ruta /
GET http://localhost:3000/
Accept: text/plain

### Eco
GET http://localhost:3000/echo?mensaje='hola 2'
Accept: application/json

### Obtener todos los usuarios
GET http://localhost:3000/usuarios
Accept: application/json

###

### Obtener un usuario por ID
GET http://localhost:3000/usuario/3
Accept: application/json

###

### Crear un nuevo usuario
POST http://localhost:3000/usuario
Content-Type: application/json

{
  "id": 3,
  "nombre": "Valentina",
  "apellido": "Paz"
}

### Ruta inexistente
GET http://localhost:3000/cualquier-cosa
Accept: application/json
